# Generated by Django 5.0.7 on 2024-08-03 16:24

from django.db import migrations, models

def set_default_values(apps, schema_editor):
    JobListing = apps.get_model('jobapp', 'JobListing')
    JobListing.objects.filter(company__isnull=True).update(company='Unknown')
    
class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_industry',
            field=models.CharField(default='Unkown', max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_key_info',
            field=models.TextField(default='No key information provided'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
