# Generated by Django 5.0.7 on 2024-08-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_joblisting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(default='Unkown', max_length=255),
        ),
    ]
