# Generated by Django 5.0.7 on 2024-08-03 17:05

from django.db import migrations

def update_existing_records(apps, schema_editor):
    JobListing = apps.get_model('jobapp', 'JobListing')
    JobListing.objects.filter(company__isnull=True).update(company='Unknown')
    JobListing.objects.filter(job_industry__isnull=True).update(job_industry='Unknown')
    JobListing.objects.filter(job_description__isnull=True).update(job_description='No description provided')
    JobListing.objects.filter(job_key_info__isnull=True).update(job_key_info='No key information provided')
class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_joblisting_company_and_more'),
    ]

    operations = [
        migrations.RunPython(update_existing_records),
    ]
