# Generated by Django 5.0.7 on 2024-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_auto_20240803_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.TextField(default='No description provided'),
        ),
    ]
