# Generated by Django 5.0.7 on 2024-08-03 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_joblisting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
